# Generated by Django 5.1 on 2025-09-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
